"""MemALL REST API (FastAPI) — 28 routes covering all MCP functionality.

Auto-generated by adapter mapping. Bind to 127.0.0.1:8199 by default.
"""

import json
import os
import uvicorn
from pathlib import Path
from fastapi import FastAPI, Query, Request, Request
from fastapi.staticfiles import StaticFiles
from fastapi.responses import RedirectResponse
from fastapi.responses import RedirectResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional

from memall.core.thin_waist import (
    capture, retrieve, connect, traverse, timeline,
    smart_store, store_batch, update, vector_search,
)
from memall.core.models import MemoryInput
from memall.pipeline.session import session_start, session_end, session_summary
from memall.pipeline.persona import generate_persona, get_evolution, generate_profile_3layer
from memall.pipeline.ask import ContextAssembler
from memall.pipeline.forget import (
    forget_expired, forget_low_value, forget_review, forget_stats, forget_step,
)
from memall.pipeline.adaptive import adaptive_step, adaptive_report
from memall.pipeline.security import (
    audit_sensitive, set_permission, check_access,
    list_agents_by_permission, security_score,
)
from memall.pipeline.ops import (
    merge_memories, split_memory, tag_memory, batch_tag,
    batch_archive, batch_restore, deduplicate,
)
from memall.mcp.federation_tools import (
    fed_query, fed_publish, fed_conflicts, auto_inject, auto_extract,
)

app = FastAPI(title="memall", version="0.1.0",
              docs_url="/docs", redoc_url="/redoc")

# CORS — restrict to localhost and file:// access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://127.0.0.1:8199", "http://localhost:8199", "file://"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Frontend static files ──
# In dev mode the frontend is at project_root/frontend/
# In installed mode it could be at package_dir/frontend/
_frontend_dir = None
for candidate in [
    Path(__file__).resolve().parent.parent.parent.parent / "frontend",  # dev
    Path(__file__).resolve().parent / "frontend",                        # installed
]:
    if candidate.exists():
        _frontend_dir = candidate
        break

if _frontend_dir:
    app.mount("/static", StaticFiles(directory=str(_frontend_dir)), name="frontend")


    @app.get("/")
    async def serve_frontend():
        index = _frontend_dir / "index.html"
        if index.exists():
            from fastapi.responses import HTMLResponse
            return HTMLResponse(index.read_text(encoding="utf-8"))
        return {"status": "ok", "frontend": "not found"}


    @app.get("/api/routes")
    async def list_routes():
        """Return all available API routes for frontend discovery."""
        routes_list = []
        for route in app.routes:
            if hasattr(route, "methods") and hasattr(route, "path"):
                path = route.path
                for m in route.methods:
                    if m in ("GET", "POST", "PUT", "DELETE"):
                        routes_list.append({"method": m, "path": path})
        return {"routes": routes_list}


# ══════════════════════════════════════════════════════════════════
# Pydantic Request Models
# ══════════════════════════════════════════════════════════════════

class CaptureRequest(BaseModel):
    content: str
    owner: str = ""
    agent_name: str = ""
    subject: str = ""
    project: str = ""
    category: str = "general"
    level: str = "P2"

class UpdateRequest(BaseModel):
    memory_id: int
    content: Optional[str] = None
    category: Optional[str] = None
    project: Optional[str] = None
    summary: Optional[str] = None
    level: Optional[str] = None

class SmartStoreRequest(BaseModel):
    content: str
    owner: str = ""
    agent_name: str = ""
    subject: str = ""
    project: str = ""
    category: str = "general"
    level: str = "P2"
    dedup_threshold: float = 0.85

class BatchStoreItem(BaseModel):
    content: str
    owner: str = ""
    agent_name: str = ""
    subject: str = ""
    project: str = ""
    category: str = "general"
    level: str = "P2"

class ConnectRequest(BaseModel):
    source_id: int
    target_id: int
    relation_type: str = "refines"
    weight: float = 1.0

class SessionStartRequest(BaseModel):
    agent_name: str = ""
    auto_inject: bool = True

class SessionEndRequest(BaseModel):
    session_id: str
    auto_extract: bool = False

class AskRequest(BaseModel):
    question: str
    mode: str = "stance"
    agent_name: Optional[str] = None
    scope: str = "local"

class ForgetRequest(BaseModel):
    action: str = "all"
    days: int = 90
    agent_name: Optional[str] = None

class SecurityRequest(BaseModel):
    action: str
    agent_name: Optional[str] = None
    level: Optional[str] = None
    requester: Optional[str] = None
    target: Optional[str] = None

class OpsRequest(BaseModel):
    action: str
    source_id: Optional[int] = None
    target_id: Optional[int] = None
    memory_id: Optional[int] = None
    delimiter: Optional[str] = None
    tags: Optional[list[str]] = None
    mode: str = "add"
    agent_name: Optional[str] = None
    category: Optional[str] = None
    days: Optional[int] = None
    threshold: float = 0.85

class FedPublishRequest(BaseModel):
    memory_id: int
    source_agent: str = ""
    trust_level: str = "family"
    category: str = ""

class GatewayRequest(BaseModel):
    action: str
    port: int = 9919
    agent_name: Optional[str] = None
    file_path: Optional[str] = None
    address: Optional[str] = None
    query: Optional[str] = None
    max_peers: int = 3


# ══════════════════════════════════════════════════════════════════
# 1. Core CRUD
# ══════════════════════════════════════════════════════════════════

@app.post("/memories")
def api_capture(req: CaptureRequest):
    """Store a memory."""
    mid = capture(MemoryInput(**req.model_dump()))
    return {"id": mid, "status": "ok"}

@app.get("/memories/search")
def api_search(query: str = "", owner: str = "", agent_name: str = "",
               category: str = "", limit: int = 20, offset: int = 0):
    """Search memories."""
    results = retrieve(query, owner=owner, agent_name=agent_name,
                       category=category, limit=limit)
    if not isinstance(results, list):
        results = [results] if results else []
    try:
        from memall.core.db import get_conn
        conn2 = get_conn()
        extra = {}
        for r in results[:limit]:
            row = conn2.execute("SELECT subject, summary, project, created_at, updated_at, tags, metadata, access_count FROM memories WHERE id = ?", (r.id,)).fetchone()
            extra[r.id] = dict(row) if row else {}
        conn2.close()
    except Exception:
        extra = {}
    result_list = []
    for r in results:
        e = extra.get(r.id, {})
        result_list.append({
            "id": r.id, "content": r.content[:200] if r.content else "",
            "subject": e.get("subject", ""), "summary": e.get("summary", ""),
            "category": r.category, "level": r.level,
            "agent_name": r.agent_name, "project": e.get("project", ""),
            "tags": e.get("tags", "[]"), "metadata": e.get("metadata", "{}"),
            "access_count": e.get("access_count", 0),
            "created_at": e.get("created_at", r.occurred_at or ""),
            "updated_at": e.get("updated_at", ""),
        })
    return result_list

@app.get("/memories/vector-search")
def api_vector_search(query: str = Query(...), top_k: int = 10):
    """Semantic vector search."""
    result = vector_search(query, top_k)
    return result

@app.put("/memories")
def api_update(req: UpdateRequest):
    """Update a memory's fields."""
    kwargs = {k: v for k, v in req.model_dump().items()
              if v is not None and k != "memory_id"}
    ok = update(req.memory_id, **kwargs)
    return {"status": "ok" if ok else "error"}

@app.post("/memories/smart-store")
def api_smart_store(req: SmartStoreRequest):
    """Store with automatic dedup (hash + semantic)."""
    result = smart_store(**req.model_dump())
    return result

@app.post("/memories/batch")
def api_batch_store(items: list[BatchStoreItem]):
    """Batch store multiple memories."""
    result = store_batch([i.model_dump() for i in items])
    return result

@app.get("/memories/stats")
def root_memories_stats():
    from memall.core.db import get_conn
    conn = get_conn()
    total = conn.execute("SELECT COUNT(*) FROM memories").fetchone()[0]
    recent = conn.execute("SELECT COUNT(*) FROM memories WHERE created_at >= datetime('now', '-24 hours')").fetchone()[0]
    by_level = dict(conn.execute("SELECT level, COUNT(*) as cnt FROM memories GROUP BY level").fetchall())
    conn.close()
    return {"success": True, "data": {"total": total, "total_memories": total, "recent_24h": recent, "by_level": by_level, "total_links": 0, "total_agents": len(by_level)}}


@app.get("/memories/{memory_id}")
def api_get(memory_id: str):
    """Get a memory by ID."""
    try:
        mid = int(memory_id)
    except ValueError:
        return {"error": "invalid id"}
    r = retrieve(mid)
    if not r:
        return {"error": "not found"}
    return {"id": r.id, "content": r.content, "category": r.category,
            "level": r.level, "agent_name": r.agent_name, "subject": r.subject,
            "summary": r.summary, "created_at": r.created_at}

@app.get("/timeline")
def api_timeline(query: str = "", hours: int = 24, category: str = "",
                project: str = "", limit: int = 50, days: Optional[int] = None):
    """Get time-ordered memories."""
    items = timeline(query=query, hours=hours, category=category,
                     project=project, limit=limit, days=days)
    return [{"id": r.id, "content": r.content, "category": r.category,
             "level": r.level, "occurred_at": r.occurred_at} for r in items]


# ══════════════════════════════════════════════════════════════════
# 2. Graph & Relations
# ══════════════════════════════════════════════════════════════════

@app.post("/edges")
def api_connect(req: ConnectRequest):
    """Create a relationship between two memories."""
    eid = connect(source_id=req.source_id, target_id=req.target_id,
                  relation_type=req.relation_type, weight=req.weight)
    return {"id": eid, "status": "ok"}

@app.get("/graph/search")
def api_graph_search(node_id: int, depth: int = 1, relation_filter: str = ""):
    """Alias for traverse — graph exploration."""
    return api_traverse(node_id, depth, relation_filter)

@app.get("/graph/{node_id}")
def api_traverse(node_id: int, depth: int = 1, relation_filter: str = ""):
    """Explore the knowledge graph from a memory."""
    kwargs = {"node_id": node_id, "depth": min(depth, 5)}
    if relation_filter:
        kwargs["relation_filter"] = relation_filter
    return _ok(traverse(**kwargs))


# ══════════════════════════════════════════════════════════════════
# 3. Persona & Insights
# ══════════════════════════════════════════════════════════════════

@app.get("/persona/{agent_name}")
def api_persona(agent_name: str, evolution: bool = False, window_days: int = 30):
    """Get agent persona."""
    p = generate_persona(agent_name)
    if evolution:
        p["evolution"] = get_evolution(agent_name, window_days)
    return p

@app.get("/persona/{agent_name}/profile")
def api_persona_profile(agent_name: str, layer: str = "all"):
    """Get full 3-layer agent profile."""
    return generate_profile_3layer(agent_name)

@app.post("/ask")
def api_ask(req: AskRequest):
    """Query digital twin — stance/pattern/predict."""
    result = ContextAssembler.ask(
        query=req.question, mode=req.mode,
        subject=req.agent_name or "", scope=req.scope,
    )
    return result


# ══════════════════════════════════════════════════════════════════
# 4. Session Management
# ══════════════════════════════════════════════════════════════════

@app.post("/sessions")
def api_session_start(req: SessionStartRequest):
    """Start a new session (optionally inject context)."""
    result = session_start(agent_name=req.agent_name, auto_inject=req.auto_inject)
    return result

@app.post("/sessions/{session_id}/end")
def api_session_end(session_id: str, auto_extract: bool = False):
    """End a session and optionally extract facts."""
    result = session_end(session_id, auto_extract=auto_extract)
    return result

@app.get("/sessions/{session_id}")
def api_session_summary(session_id: str):
    """Get session summary."""
    result = session_summary(session_id=session_id)
    return result

@app.get("/sessions")
def api_sessions_list(agent_name: str = "", limit: int = 5):
    """List recent sessions."""
    result = session_summary(agent_name=agent_name, limit=limit)
    return result


# ══════════════════════════════════════════════════════════════════
# 5. Federation
# ══════════════════════════════════════════════════════════════════

@app.get("/federation/query")
def api_fed_query(query: str = "", agent_name: str = "",
                  category: str = "", trust_level: str = "", limit: int = 20):
    """Cross-agent memory query."""
    return fed_query(query, agent_name, category, trust_level, limit)

@app.post("/federation/publish")
def api_fed_publish(req: FedPublishRequest):
    """Publish memory to shared space."""
    return fed_publish(req.memory_id, req.source_agent,
                       req.trust_level, req.category)

@app.get("/federation/conflicts")
def api_fed_conflicts(limit: int = 20):
    """List unresolved conflicts."""
    return fed_conflicts(limit)

@app.post("/federation/inject/{agent_name}")
def api_fed_inject(agent_name: str):
    """Auto-inject agent context (for session_start)."""
    return auto_inject(agent_name)

@app.post("/federation/extract/{session_id}")
def api_fed_extract(session_id: str):
    """Auto-extract session facts (for session_end)."""
    return auto_extract(session_id)


# ══════════════════════════════════════════════════════════════════
# 6. Forgetting & Adaptive
# ══════════════════════════════════════════════════════════════════

@app.post("/forget")
def api_forget(req: ForgetRequest):
    """Automatic forgetting — TTL expiry + low-value decay."""
    days = req.days
    agent = req.agent_name
    actions = {
        "expired": lambda: forget_expired(days, agent),
        "low_value": lambda: forget_low_value(agent),
        "review": lambda: forget_review(days, agent),
        "stats": lambda: forget_stats(),
        "all": lambda: forget_step(days, agent),
    }
    fn = actions.get(req.action)
    return fn() if fn else {"error": f"unknown action: {req.action}"}

@app.post("/adaptive")
def api_adaptive(agent_name: Optional[str] = None):
    """Run AI adaptive subsystem — clean/index/distill/report."""
    if agent_name:
        return adaptive_step(agent_name=agent_name)
    return adaptive_report()

@app.get("/adaptive/report")
def api_adaptive_report():
    """Get adaptive subsystem status report."""
    return adaptive_report()


# ══════════════════════════════════════════════════════════════════
# 7. Security Governance
# ══════════════════════════════════════════════════════════════════

@app.post("/security")
def api_security(req: SecurityRequest):
    """Security governance — audit/permit/check/score/list."""
    actions = {
        "audit": lambda: audit_sensitive(agent_name=req.agent_name),
        "permit": lambda: set_permission(req.agent_name, req.level),
        "check": lambda: check_access(req.requester, req.target),
        "score": lambda: security_score(),
        "list": lambda: list_agents_by_permission(req.level),
    }
    fn = actions.get(req.action)
    if not fn:
        return {"error": f"unknown action: {req.action}"}
    try:
        return fn()
    except Exception as e:
        return {"error": str(e)}


# ══════════════════════════════════════════════════════════════════
# 8. Memory Operations
# ══════════════════════════════════════════════════════════════════

@app.post("/ops")
def api_ops(req: OpsRequest):
    """Memory ops — merge/split/tag/batch-tag/archive/restore/dedup."""
    actions = {
        "merge": lambda: merge_memories(req.source_id, req.target_id),
        "split": lambda: split_memory(req.memory_id, req.delimiter),
        "tag": lambda: tag_memory(req.memory_id, req.tags, req.mode),
        "batch_tag": lambda: batch_tag(req.agent_name, req.category, req.tags, req.mode),
        "archive": lambda: batch_archive(req.agent_name, req.days),
        "restore": lambda: batch_restore(req.agent_name),
        "dedup": lambda: deduplicate(req.agent_name, req.threshold),
    }
    fn = actions.get(req.action)
    return fn() if fn else {"error": f"unknown action: {req.action}"}

@app.get("/ops/dedup")
def api_dedup_check(agent_name: str = "", threshold: float = 0.85):
    """Check for duplicate memories (preview)."""
    return {"note": "Use POST /ops with action=dedup to execute"}


# ══════════════════════════════════════════════════════════════════
# 9. Gateway
# ══════════════════════════════════════════════════════════════════

@app.post("/gateway")
def api_gateway(req: GatewayRequest):
    """Gateway operations — start/stop/export/import/discover/pair/peers/federated."""
    from memall.gateway import (
        export_bundle, import_bundle, start_discovery, stop_discovery,
        discover_peers, pair_with_peer, list_peers, federated_retrieve,
    )
    actions = {
        "export": lambda: export_bundle(req.agent_name),
        "discover": lambda: discover_peers(timeout=5),
        "peers": lambda: list_peers(),
        "federated": lambda: federated_retrieve(req.query, req.max_peers),
    }
    fn = actions.get(req.action)
    if fn:
        return fn()
    return {"error": f"gateway action '{req.action}' available via aiohttp server on port {req.port}"}


# ══════════════════════════════════════════════════════════════════
# 10. Database Maintenance
# ══════════════════════════════════════════════════════════════════

@app.post("/db/optimize")
def api_db_optimize():
    """ANALYZE + VACUUM + PRAGMA optimize."""
    from memall.core.db import optimize_db
    return optimize_db()

@app.get("/agents")
def api_agents():
    """List all agents with their memory counts."""
    from memall.core.thin_waist import _pool_conn
    with _pool_conn() as conn:
        rows = conn.execute(
            "SELECT agent_name, COUNT(*) as cnt FROM memories WHERE agent_name != '' AND agent_name IS NOT NULL GROUP BY agent_name ORDER BY cnt DESC"
        ).fetchall()
        return _ok([{"name": r["agent_name"], "count": r["cnt"]} for r in rows])

@app.get("/db/stats")
def api_db_stats():
    """Database statistics."""
    from memall.core.db import db_stats
    return db_stats()

@app.post("/db/vacuum")
def api_db_vacuum():
    """Reclaim disk space."""
    from memall.core.db import vacuum_db
    return vacuum_db()


# ══════════════════════════════════════════════════════════════════
# Reflection / L6 Dashboard
# ══════════════════════════════════════════════════════════════════

@app.get("/reflection/dashboard")
def api_reflection_dashboard(days: int = 30):
    """L6 reflection dashboard data: density, quality, topics, chain."""
    from memall.pipeline.observe import reflection_dashboard
    return _ok(reflection_dashboard(days=days))


@app.post("/reflection/interact")
def api_reflection_interact(body: dict):
    """Interact with an L6 reflection: agree/disagree/probe."""
    memory_id = body["memory_id"]
    action = body["action"]
    context = body.get("context", "")
    from memall.core.db import get_conn
    import json as _json
    conn = get_conn()
    try:
        row = conn.execute("SELECT id, level, metadata FROM memories WHERE id = ?", (memory_id,)).fetchone()
        if not row:
            return {"error": f"memory {memory_id} not found"}
        if row["level"] != "L6":
            return {"error": f"memory {memory_id} is not L6"}
        meta = _json.loads(row["metadata"]) if row["metadata"] else {}
        interactions = meta.get("interactions", [])
        interactions.append({"action": action, "context": context, "timestamp": datetime.now(timezone.utc).isoformat()})
        meta["interactions"] = interactions
        conn.execute("UPDATE memories SET metadata = ?, updated_at = ? WHERE id = ?",
                     (_json.dumps(meta), datetime.now(timezone.utc).isoformat(), memory_id))
        conn.commit()
        return {"status": "ok", "memory_id": memory_id, "action": action, "total_interactions": len(interactions)}
    finally:
        conn.close()


# ══════════════════════════════════════════════════════════════════
# Pipeline
# ══════════════════════════════════════════════════════════════════

@app.post("/pipeline/run")
def api_run_pipeline(
    include_reflect: bool = True,
    include_distill: bool = True,
    include_integrate: bool = True,
    include_persona: bool = True,
):
    """Run the full memory pipeline."""
    from memall.pipeline.pipeline import run_pipeline
    result = run_pipeline(
        include_reflect=include_reflect,
        include_distill=include_distill,
        include_integrate=include_integrate,
        include_persona=include_persona,
    )
    return result


# ══════════════════════════════════════════════════════════════════
# Migrations
# ══════════════════════════════════════════════════════════════════

@app.get("/migrations/status")
def api_migration_status():
    """Get migration status: pending and applied migrations."""
    from memall.core.db import get_conn
    from memall.migrations import get_migration_status
    conn = get_conn()
    try:
        return get_migration_status(conn)
    finally:
        conn.close()


@app.post("/migrations/run")
def api_run_migrations():
    """Run all pending migrations."""
    from memall.core.db import get_conn, DB_PATH
    from memall.migrations import run_migrations
    conn = get_conn()
    try:
        result = run_migrations(conn, db_path=str(DB_PATH))
        conn.commit()
        return result
    finally:
        conn.close()


# ══════════════════════════════════════════════════════════════════
# Health
# ══════════════════════════════════════════════════════════════════



def root_memories_stats():
    '''v30 compat: stats overview.'''
    from memall.core.db import get_conn
    conn = get_conn()
    total = conn.execute("SELECT COUNT(*) FROM memories").fetchone()[0]
    recent = conn.execute("SELECT COUNT(*) FROM memories WHERE created_at >= datetime('now', '-24 hours')").fetchone()[0]
    by_level = dict(conn.execute("SELECT level, COUNT(*) as cnt FROM memories GROUP BY level").fetchall())
    conn.close()
    return {"success": True, "data": {"total": total, "total_memories": total, "recent_24h": recent, "by_level": by_level, "total_links": 0, "total_agents": len(by_level)}}

@app.get("/memories")
def root_list_memories(request: Request, hours: int = 8760, limit: int = 50, offset: int = 0, level: str = ""):
    '''v30 compat: list memories. Returns HTML (SPA) for browsers, JSON for API clients.'''
    accept = request.headers.get("accept", "")
    if "text/html" in accept and _frontend_dir:
        index = _frontend_dir / "index.html"
        if index.exists():
            from fastapi.responses import HTMLResponse
            return HTMLResponse(index.read_text(encoding="utf-8"))
    from memall.core.db import get_conn
    conn = get_conn()
    try:
        where = "1=1"
        params = []
        if level:
            where += " AND level = ?"
            params.append(level)
        total = conn.execute(f"SELECT COUNT(*) FROM memories WHERE {where}", params).fetchone()[0]
        rows = conn.execute(f"SELECT id, content, subject as title, level, agent_name, category, project, summary, tags, created_at, updated_at, access_count, metadata FROM memories WHERE {where} ORDER BY id DESC LIMIT ? OFFSET ?", params + [limit, offset]).fetchall()
        return {"success": True, "data": {"items": [dict(r) for r in rows], "total": total}}
    finally:
        conn.close()


def root_memories_stats():
    '''v30 compat: stats overview.'''
    from memall.core.db import get_conn
    conn = get_conn()
    total = conn.execute("SELECT COUNT(*) FROM memories").fetchone()[0]
    recent = conn.execute("SELECT COUNT(*) FROM memories WHERE created_at >= datetime('now', '-24 hours')").fetchone()[0]
    by_level = dict(conn.execute("SELECT level, COUNT(*) as cnt FROM memories GROUP BY level").fetchall())
    conn.close()
    return {"success": True, "data": {"total": total, "total_memories": total, "recent_24h": recent, "by_level": by_level, "total_links": 0, "total_agents": len(by_level)}}


@app.get("/memories/search")
def root_search_memories(q: str = "", limit: int = 20):
    '''v30 compat: search memories.'''
    from memall.core.db import get_conn
    conn = get_conn()
    try:
        if q:
            rows = conn.execute("SELECT id, content, subject as title, level, agent_name, category, project, summary, tags, created_at, updated_at FROM memories WHERE content LIKE ? OR subject LIKE ? ORDER BY id DESC LIMIT ?", (f"%{q}%", f"%{q}%", limit)).fetchall()
        else:
            rows = conn.execute("SELECT id, content, subject as title, level, agent_name, category, project, summary, tags, created_at, updated_at FROM memories ORDER BY id DESC LIMIT ?", (limit,)).fetchall()
        return {"success": True, "data": {"results": [dict(r) for r in rows]}}
    finally:
        conn.close()


@app.get("/health")
def api_health():
    """Health check."""
    return {"status": "ok", "version": "0.1.0"}




_v30_dir = Path(__file__).resolve().parent.parent.parent.parent / "desktop" / "v30"
if _v30_dir.exists():
    app.mount("/v30", StaticFiles(directory=str(_v30_dir), html=True), name="v30_frontend")


def _ok(data=None):
    return {"success": True, "data": data}


@app.get("/v30api/memories")
def v30_list_memories(
    hours: int = 8760,
    limit: int = 50, offset: int = 0,
    page: int = 1, per_page: int = 50,
    level: str = "", q: str = "", agent: str = "", category: str = "", period: str = "",
    sort_by: str = "created_at", sort_order: str = "desc"
):
    from memall.core.db import get_conn
    conn = get_conn()
    try:
        where = "1=1"
        params = []

        if level:
            where += " AND level = ?"
            params.append(level)
        if q:
            where += " AND (content LIKE ? OR subject LIKE ? OR agent_name LIKE ? OR category LIKE ?)"
            like = f"%{q}%"
            params += [like, like, like, like]
        if agent:
            where += " AND agent_name = ?"
            params.append(agent)
        if category:
            where += " AND category = ?"
            params.append(category)
        if period:
            from datetime import datetime, timezone, timedelta
            period_days = {
                "today": 0,
                "3d": 3,
                "week": 7,
                "month": 30,
            }
            days = period_days.get(period)
            if days is not None:
                where += " AND created_at >= ?"
                params.append((datetime.now(timezone.utc) - timedelta(days=days)).isoformat())

        total = conn.execute(f"SELECT COUNT(*) FROM memories WHERE {where}", params).fetchone()[0]

        allowed_sort = {"id","created_at","updated_at","level","agent_name","category","project","access_count"}
        col = sort_by if sort_by in allowed_sort else "created_at"
        dir_ = "DESC" if sort_order.lower() == "desc" else "ASC"

        use_page = page > 1 or per_page != 50
        if use_page:
            limit = per_page
            offset = (page - 1) * per_page

        rows = conn.execute(
            f"SELECT id, content, subject as title, level, agent_name, category, project, summary, tags, created_at, updated_at, access_count, metadata FROM memories WHERE {where} ORDER BY {col} {dir_} LIMIT ? OFFSET ?",
            params + [limit, offset],
        ).fetchall()
        return _ok({"items": [dict(r) for r in rows], "total": total, "page": page, "per_page": limit})
    finally:
        conn.close()


@app.get("/v30api/memories/stats")
def v30_memories_stats():
    from memall.core.db import get_conn
    conn = get_conn()
    total = conn.execute("SELECT COUNT(*) FROM memories").fetchone()[0]
    recent = conn.execute("SELECT COUNT(*) FROM memories WHERE created_at >= datetime('now', '-24 hours')").fetchone()[0]
    by_level = dict(conn.execute("SELECT level, COUNT(*) as cnt FROM memories GROUP BY level").fetchall())
    edges = conn.execute("SELECT COUNT(*) FROM edges").fetchone()[0]
    conn.close()
    return _ok({"total": total, "total_memories": total, "recent_24h": recent, "by_level": by_level, "total_links": edges, "total_agents": len(by_level)})


@app.get("/v30api/memories/{memory_id}")
def v30_get_memory(memory_id: int):
    from memall.core.db import get_conn
    conn = get_conn()
    row = conn.execute("SELECT id, content, subject as title, level, agent_name, category, project, summary, tags, created_at, updated_at, access_count, metadata FROM memories WHERE id = ?", (memory_id,)).fetchone()
    conn.close()
    return _ok(dict(row) if row else None)


@app.delete("/v30api/memories/{memory_id}")
def v30_delete_memory(memory_id: int):
    from memall.core.db import get_conn
    conn = get_conn()
    conn.execute("DELETE FROM edges WHERE source_id = ? OR target_id = ?", (memory_id, memory_id))
    conn.execute("DELETE FROM memories WHERE id = ?", (memory_id,))
    conn.commit()
    conn.close()
    return _ok({"deleted": memory_id})


@app.post("/v30api/memories")
def v30_create_memory(body: dict):
    mid = capture(MemoryInput(content=body.get("content", ""), level=body.get("level", "P2"), agent_name=body.get("agent_name", "desktop"), subject=body.get("title", ""), category=body.get("category", "general"), project=body.get("project", ""), summary=body.get("summary", "")))
    return _ok({"id": mid})


@app.put("/v30api/memories/{memory_id}")
def v30_update_memory(memory_id: int, body: dict):
    from memall.core.db import get_conn
    conn = get_conn()
    for field in ("content", "level", "category", "project", "summary"):
        if field in body:
            conn.execute(f"UPDATE memories SET {field} = ?, updated_at = datetime('now') WHERE id = ?", (body[field], memory_id))
    if "title" in body:
        conn.execute("UPDATE memories SET subject = ?, updated_at = datetime('now') WHERE id = ?", (body["title"], memory_id))
    if "tags" in body:
        conn.execute("UPDATE memories SET tags = ?, updated_at = datetime('now') WHERE id = ?", (body["tags"], memory_id))
    conn.commit()
    conn.close()
    return _ok({"id": memory_id})


# ══════════════════════════════════════════════════════════════════
# Server Entry
# ══════════════════════════════════════════════════════════════════

def serve_http(port: int = 8199):
    """Start HTTP API server on localhost."""
    uvicorn.run(app, host="127.0.0.1", port=port, log_level="info",
                timeout_keep_alive=5)
